#!/bin/bash
## stop the script if an error occurs
set -e

function prepare {
  TEMP_DIRECTORY=/tmp
  TEMPFILE=`mktemp $TEMP_DIRECTORY/ScriptXXXXX|sed -e 's/\.//g'`
  CLASS_NAME=`basename "$TEMPFILE"`
  JAVA_SOURCE=$TEMPFILE.java
}

function compile {
  ## change the name of the class to match the file
  sed "s/public class \w\w*/public class $CLASS_NAME/" $JAVA_SOURCE.tmp >$JAVA_SOURCE
 
  ## compile the java
  javac -classpath .:$CLASSPATH $JAVA_SOURCE 
}

function run {
  ## run the class 
  ## you may wish to add additional parameters to come
  ## through as args to the main method
  java -classpath $TEMP_DIRECTORY:$CLASSPATH $CLASS_NAME $1 $2 $3 $4 $5 $6 $7 $8
}

prepare
cp $1 $JAVA_SOURCE.tmp
compile
run $2 $3 $4 $5 $6 $7 $8 $9

